# Generated by Django 5.0.3 on 2024-03-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_in_cart',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('DF', 'Dry food'), ('WF', 'Wet food'), ('VD', 'Veterinary diet'), ('SC', 'Sand/Crystal cats'), ('SN', 'Snacks'), ('BL', 'Ball'), ('TR', 'Transport'), ('LC', 'Leashes and collars')], max_length=2),
        ),
    ]
